// <auto-generated />
using System;
using ERWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERWeb.Pages.DateExchangeRateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DateExchangeRates");
                });

            modelBuilder.Entity("ERWeb.Pages.DateExchangeRateModel", b =>
                {
                    b.OwnsMany("ExchangeRates.ExchangeRate", "ExchangeRates", b1 =>
                        {
                            b1.Property<Guid>("DateExchangeRateModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Abbreviation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasAnnotation("Relational:JsonPropertyName", "Cur_Abbreviation");

                            b1.Property<decimal>("OfficialRate")
                                .HasColumnType("decimal(18,2)")
                                .HasAnnotation("Relational:JsonPropertyName", "Cur_OfficialRate");

                            b1.HasKey("DateExchangeRateModelId", "Id");

                            b1.ToTable("ExchangeRate");

                            b1.WithOwner()
                                .HasForeignKey("DateExchangeRateModelId");
                        });

                    b.Navigation("ExchangeRates");
                });
#pragma warning restore 612, 618
        }
    }
}
